name: challange_beclever
description: "Interview challange"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

# Assets
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

# Navitagion
  go_router: ^14.3.0

# Utils
  intl: ^0.19.0

# UI
  pin_code_fields: ^8.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.1
  build_runner: ^2.4.13

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
